/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    'Baseblue.button': typeof import('./src/components/buttons/baseblue.button.vue')['default']
    'BaseBlue.button': typeof import('./src/components/buttons/BaseBlue.button.vue')['default']
    BaseBlueButton: typeof import('./src/components/buttons/BaseBlueButton.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    Header: typeof import('./src/layouts/header.vue')['default']
    Menu: typeof import('./src/layouts/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
